### ISSUE TITLE
Some messages flood my console (-dev)

### ISSUE THREAD

**Issue by souvikdas95** [s1lentq/ReGameDLL_CS#104]
Got a velocity too low on weaponbox (Randomly)
Got a velocity too low on item_thighpack (Randomly)
Client Rodrii` started recording. Send full update. (Occurs everytime a player connects)
Warning:  Ignoring unreliable datagram for <name>, would overflow (This message occurs like more than 2000-3000 lines!)

**Comment by Kushfield** [comment]
As I am a surfer and as such use 131 fps (which used to be possible only with developer mode on, and still is with the older versions of the game), I can confidently say that I've been seeing these kinds of messages every now and then for as long as I can remember. I am not 100% sure, but my guess is that all these messages are only generated on the client-side.

Although some of the messages might be signs of some deeper issues in the server or in the game client, the messages themselves are not bugs by any means. This is what developer mode is designed for - to give maximal feedback to developers in order to ease their work.

**Comment by In-line** [comment]
@souvikdas95 I think It doesn't refer to ReGameDLL_CS. Did you tried it with default gamedll?

From rehlds:
./engine/sv_phys.cpp:106:			Con_DPrintf("Got a velocity too low on %s\n", &pr_strings[ent->v.classname]);
./engine/sv_user.cpp:742:	Con_DPrintf("Client %s started recording. Send full update.\n", host_client->name);
./engine/sv_main.cpp:4702:			Con_DPrintf("Warning: Ignoring unreliable datagram for %s, would overflow on msg\n", client->name)

**Comment by In-line** [comment]
Closing as non active.
