### ISSUE TITLE
metamod p38 not working regamedll

### ISSUE THREAD

**Issue by csoyuncu** [s1lentq/ReGameDLL_CS#267]
please fix this problem thanks.

**Comment by Dr-Strange91** [comment]
https://github.com/jkivilin/metamod-p/issues/8#issuecomment-365098858

You posted this ... Log.

I believe, this could be the solution.

Question : Do not respond to the game version command , what should I do?
Answer : First you need to perform some steps:

You need to make sure that you put mp.dll (For Windows ) or cs.so (For Linux ) in the gamedir/dlls /directory .
If you have a Metamod , you should make sure that Metamod downloads it to your library mp.dll/cs.so , write command meta game and you will see in "dll pathname" path to the library that loaded Metamod .

In the gamedir/dlls folder there should not be cs_i386.so and backup of the original cs.so library , Metamod will download them anyway , since it considers them to be priority than ReGameDLL . ( Tip: You can directly tell Metamod which library to load, for this go to the Metamod folder ( addons / metamod ), open config.ini ( if not, create config.ini ) and add the line:

gamedll dlls/cs.so

**Comment by csoyuncu** [comment]
@Dr-Strange91 you test new metamod version with rehlds&regamedll and write me later...

**Comment by In-line** [comment]
@csoyuncu If problem was solved close issue.

**Comment by csoyuncu** [comment]
yes problem has been solved. Thanks !

**Comment by Freeman-AM** [comment]
I believe this bug is still alive.

**Comment by greygrim** [comment]
> I believe this bug is still alive.

ofc it is....
