### ISSUE TITLE
mp_buy_anywhere not works!

### ISSUE THREAD

**Issue by 2020karaulov2020** [s1lentq/ReGameDLL_CS#604]
mp_buy_anywhere not works!

'buy' command not works, and 'buyzone' icon not shows.

Only F1 F2 (autobuy/rebuy) works!

**Comment by 2020karaulov2020** [comment]
__This cvar activated at last round of map by plugin!__

**Comment by StevenKal** [comment]
On some maps which does not have a "func_buyzone" (so default map spawns used), yes, no buy icon appears when "mp_buytime" set and with "mp_buy_anywhere" enabled too.
I think it is due to the "CSGameRules()->CanPlayerBuy(this)" check on player.cpp's L6629 which internally check again for buy zone signals, and which fails, so signals for buy zone are not set, and the alternative code below calling "OLD_CheckBuyZone" is supposed to be called, but has also received a "if (!CSGameRules()->CanPlayerBuy(pPlayer))" fix at the beginning which prevents the internal (following) code to be called.
A rework of those parts need to be done for "mp_buy_anywhere" support.

**Comment by StevenKal** [comment]
This is probably due to a map having CHalfLifeMultiplay's "m_b<T|CT>CantBuy" booleans on true on such maps (via "info_map_parameters" entity), so no buy icon is showed.

**Comment by 2020karaulov2020** [comment]
> This is probably due to a map having CHalfLifeMultiplay's "m_b<T|CT>CantBuy" booleans on true on such maps (via "info_map_parameters" entity), so no buy icon is showed.

No
