### ISSUE TITLE
mp_buytime not works or mp_buy_anywhere not works!

### ISSUE THREAD

**Issue by 2020karaulov2020** [s1lentq/ReGameDLL_CS#606]
If activated mp_buy_anywhere after round start, players can't buy items in buyzone. 

**Need move away and then go back to buyzone.**

**Comment by StevenKal** [comment]
This does not happen when I quickly test exactly the way you said, for me it instantly turns on/off the buy icon when I switch the CVar "mp_buy_anywhere".

Does this happen on all the maps or only on one/some specific?
Are you sure "mp_buytime" is not set to 0?
Did you tested with a "raw" ReGameDLL_CS binary (not a modified one by yourself with possible mistakes you could have been made on it)?
Did you tested with a raw game (not with some [badly made] plugins which could fuck up the behavior?
...

**Comment by 2020karaulov2020** [comment]
I checking it with plugin "map manager modular" (add mp_buytime 999 and mp_buy_anywhere 1 at last round voting)

**Comment by StevenKal** [comment]
What do you do man? You want to see who is answering here by posting random problems which sounds "kind of fake", or have some fun? I say that because you posted the issue twice, and closed it without explaining why, or if you figured out the problem.

Besides, if the problem "exists for real", you need to give more details about "how to replicate exactly", people are not clairvoyants usually.
Also, I was unable to replicate your problem, and even by looking at the source I did not see a problem in the code (or this did not "jumped to my eyes directly"), and I recall you that "mp_buy_anywhere" only make the "buy capabilities" not limited to the default size of "func_buyzone" or 200 units radius of the player spawns, but this does not bypass other "buy limits", and still obey to them.
