### ISSUE TITLE
How the bullet spread process?

### ISSUE THREAD

**Issue by DTEX123** [s1lentq/ReGameDLL_CS#841]
I changed flSpread and m_flAccuracy but not work in game.
Where can I find the code?
Just want to change the logic.

**Comment by dystopm** [comment]
Be aware of client prediction, you may think spread is not getting changed but it actually does, but client itself is behaving like it is spreading, because you are modifying it server-side. Test it using `cl_lw 0` or spawn a beam tempentity to see the exact position where bullet hits.

To correctly alter bullet hole fx, you must disable client prediction and therefore faking a new bullet hole using tempentities.
