### ISSUE TITLE
Installation post-anniversary brings Half-Life view bobbing.

### ISSUE THREAD

**Issue by Damsen117** [s1lentq/ReGameDLL_CS#907]
What title says. After installing this on a CS 1.6 annivesary server, it makes all players have view bobbing like seen in Half-Life where our view gets tilted either left or right.
Is there any work on this for anniversary builds?

**Comment by dystopm** [comment]
Its not related to regamedll

**Comment by dystopm** [comment]
> It is, because it only happens when i install it.

Bobbing was added on the last anniversary update. ReGameDLL is a server-side modification, cl_bob cvar was changed for all steam clients. Check https://github.com/ValveSoftware/halflife issues.

If you are sure enough of your words anyway, provide more information about what are you installing, versions of everything, and multimedia if needed.

**Comment by dystopm** [comment]
> It's just a clean server. Install the latest version of a anniversary server (December 1st), and then replace the mp.dll from here. And there you have the view bobbing back again when before it didn't. It's very easily replicated. Regamedll will have to address this for anniversary builds for bringing that feature back. Try it yourself.

I tried myself in a listen server and I see the bobbing. I did not need to install regamedll. https://github.com/ValveSoftware/halflife/issues/3691

**Comment by unattendedplayer** [comment]
View bobbing is **client** related and regamedll is a **server** DLL. You should demand the "fix" from Valve themselves.

**Comment by ImBenny95** [comment]
I also experience the same thing.

**Comment by dystopm** [comment]
> I also experience the same thing.

Not regamedll related, see posts above

**Comment by eXPc023** [comment]
I think what they referring to is sv_rollangle which is 0 by default in post-25th anniversary game DLLs. Since regameDLL was based on an older build, it doesn't have knowledge for this CVAR and sets it to 2 (engine default). Bobbing is related to client
and cannot be changed (unless you find a way to use the older client.dll without beta-style bobbing).
To fix rollangle, simply add: 
`sv_rollangle 0`
to server.cfg (listenserver.cfg if you are creating server from game).
