### ISSUE TITLE
[Question] Can i use pieces of code for an Half-Life mod?

### ISSUE THREAD

**Issue by LambdaLuke87** [s1lentq/ReGameDLL_CS#909]
hi, i have some question, can i use pieces of code of this repo for an half-life mod im making?? i know this have an license but i dont understand much about how works

aslo in case of i can use witouth problems give me the names for place the credits

**Comment by s1lentq** [comment]
Yes, you can use it in your half-life mod.
However, it's important to note that this code contains elements based on reverse-engineering of Valve's vanilla code for CS 1.6 gamedll.
If your mod involves rights or elements that conflict with reverse-engineered code, it might pose compatibility or legal issues.
Regarding credits, there's no need to specifically mention any individual names because the project has numerous contributors who have collectively contributed to its development so along with the repository link, should suffice as credit.

**Comment by LambdaLuke87** [comment]
thx for the permissions and the info!
i only interested in use func_vehicle code, and when valve do the hl 25th sdk ill replace with his code, and aslo i want to use the code of refill objets/elements on the map "UTIL_RestartOther"
