### ISSUE TITLE
Баг в mp_nadedrops

### ISSUE THREAD

**Issue by WessTorn** [s1lentq/ReGameDLL_CS#923]
Если у вас есть **одна** Flash граната и вы пытаетесь подобрать **одну** Flash гранату, то граната не поднимется.

**Comment by Vaqtincha** [comment]
Подтверждаю. Сломал его https://github.com/s1lentq/ReGameDLL_CS/pull/847

**Comment by dystopm** [comment]
> Подтверждаю. Сломал его #847

Broke why? Are you aware of your (daily) nonsense?

**Comment by WessTorn** [comment]
Подскажите пожалуйста, а как лимит гранат увеличить или сделать бесконечным?
Чтобы можно было подбирать, например, смоки больше 1-го

**Comment by Vaqtincha** [comment]
@WessTorn подождите наш dystopm сделает с багами (и никто не тестирует перед мерджем).

**Comment by WessTorn** [comment]
@Vaqtincha  Чтож вы так друг-друга не любите :D

**Comment by Vaqtincha** [comment]
@WessTorn Потому что я не люблю пиндосов англососов. И не собираюсь любить мужиков как эти заднеприводники.

**Comment by dystopm** [comment]
> @WessTorn подождите наш dystopm сделает с багами (и никто не тестирует перед мерджем).

I'm still waiting to your reasons for blaming that commit, which isn't blocking any pickup behaviour. Instead, I'll be blaming your #669 commit which added (again) bad coded logic, expected from somebody who asks other coders to clean their mess. My nonsensical dogshit comment inbox is open and waiting for your incoming self owning, "again"

> @Vaqtincha Чтож вы так друг-друга не любите :D

He's mad at me because I pwnd him on #479 - and I'm also southamerican and arguably a better coder, so guess and imagine the level of shame this poor firstworld creature must feel 😜👌🏼

> Подскажите пожалуйста, а как лимит гранат увеличить или сделать бесконечным? Чтобы можно было подбирать, например, смоки больше 1-го

What I don't understand is if you can't pick up that flashbang, or if the flashbang is picked up but not deployed immediately. 
If you want to increase flashbang carry limit, use [reapi's rg_set_iteminfo](https://github.com/s1lentq/reapi/blob/master/reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc) on weapon's spawn, like using Ham_Spawn on weapon_flashbang at post. 
If you want to increase this limit but on internal weapon buying system, use rg_set_weapon_info. 
If flashbang is not deployed immediately, it's because of weight properties on weapons, but I'll elaborate on this after you clarify that point.

PD: please, on english

**Comment by Vaqtincha** [comment]
Неважно как выглядит код а главное он работал до твоего кривого коммита. Иди исправ быстро.

Это русскоязычный issue и это не твое место. Иди со своим инглишом на другое место.

**Comment by WaLkZa** [comment]
> Неважно как выглядит код а главное он работал до твоего кривого коммита. Иди исправ быстро.
> 
> Это русскоязычный issue и это не твое место. Иди со своим инглишом на другое место.
> 
> С тобой все понятно заднеприводник.

Много лошо поведение. Не забравяй, че не си единствения на света, който използва кирилица.

**Comment by Vaqtincha** [comment]
@dystopm https://natribu.org/en/

**Comment by Vaqtincha** [comment]
Я всего лишь указал где сломался код а этот пидор начал оскорблять хорошего человека.

**Comment by Vaqtincha** [comment]
Демократично поступил кто-то тут. Лишь избранные могут говорить.

**Comment by StevenKal** [comment]
Yeah dysto, pwn him!
